//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Попрыженок
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }

        public int Discount
        {
            get
            {
                decimal TotalCost = ProductCount * Product.MinCostForAgent;
                if (TotalCost >= 0 & TotalCost < 10000)
                {
                    return 0;
                }
                else if (TotalCost >= 10000 & TotalCost < 50000)
                {
                    return 5;
                }
                else if (TotalCost >= 50000 & TotalCost < 150000)
                {
                    return 10;
                }
                else if (TotalCost >= 150000 & TotalCost < 500000)
                {
                    return 20;
                }
                else
                {
                    return 25;
                }
            }
        }
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
    }
}
